### PR TITLE
Add spacing between preference tabs

### PR DESCRIPTION
**Pull request by zacharee**
This is a minor cosmetic change to make the preference tabs look a little nicer. 

I also wanted to add some padding to the toolbar items themselves, but I can't figure that out (and it seems like macOS should be doing it anyway).

image

### CODE REVIEW

**Comment by lwouis** [comment]
I must confess, I'm not immediately convinced that this is an improvement. It feels like the design with extra margin is not standard. It's recommended nowhere on [the HIG](https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/toolbars/). It makes the app look different from other apps, and I don't see clearly the benefits. It also makes the code implementation have more code, and it could introduce layout regressions. We already have some layout issues:

* https://github.com/lwouis/alt-tab-macos/issues/522
* https://github.com/lwouis/alt-tab-macos/issues/1062

Be careful as well that usually you should let standard components handle themselves, so they can adapt to the various relooking of macOS versions. By that I mean that your change may look broken in another version of macOS where the toolbars look fairly different.

Overall, I feel sorry but I don't see the benefits clearly, so I don't think I could merge this change

**Comment by zacharee** [comment]
It's similar to the Xcode layout, although it looks like Xcode has fixed spacing between tabs and flexible spacing on the edges.

image

**Comment by lwouis** [comment]
I'm not sure. There is a lot of testing to do on the various macOS versions. Like how about this line here: https://github.com/lwouis/alt-tab-macos/blob/9847038f26cb9098d2af6ec0b31f55ca94333d99/src/ui/preferences-window/PreferencesWindow.swift#L32

I have never properly tested AltTab on macOS 11 or 12 as I'm still on 10.15, so there are a lot I'm not fully aware of, like the new design direction of the OSes, compatibility, maybe changes in the way we should call the APIs, maybe new dark mode stuff, etc.

**Comment by zacharee** [comment]
Maybe it would make sense to redo the toolbar entirely.

**Comment by lwouis** [comment]
> Maybe it would make sense to redo the toolbar entirely.

What do you mean exactly?

**Comment by zacharee** [comment]
> > Maybe it would make sense to redo the toolbar entirely.
> 
> What do you mean exactly? Do you mean rework the preferences overall, as in the scope of #351?

It could probably be part of that.

**Comment by lwouis** [comment]
It's been a year without activity. I'm closing the PR 🙇

**Pull request closed without merging**
