### PR TITLE
fix: adds missing return statements

### PR DESCRIPTION
**Pull request by gingerr**
so the project builds without any compile errors on macOS high sierra (10.13.x)

### CODE REVIEW

**Comment by gingerr** [comment]
My home computer system is a Hackintosh, which I currently can't update to Mojave or Catalina cause of missing NVIDIA drivers.

Strangely the project does not compile here but it does on my macBook which runs macOS Catalina (10.15.x). Maybe some Swift language update / configuration thing.

This commit fixes that.

**Comment by lwouis** [comment]
Adding back the implicit `return`s is not a big deal so I'll merge it, but overall it would be nice to understand what went wrong better on High Sierra. Ideally I would love for this project to be portable from the dev environment perspective. I did not make use of Interface Builder to reduce dependency on (different versions of) XCode for instance.

Implicit returns are a Swift feature. If you are compiling against Swift 4.2, then it should work. I'm guessing that somehow on your High Sierra machine, the project was not configured to use the proper Swift version, or maybe some OS library? That's the kind of things that may be improved by adding some `.xcconfig` file or something. I'm not an XCode expert though, so maybe somebody else can help here

**Comment by gingerr** [comment]
I see. 

It seems like to get the newest Xcode one has to use the latest macOS (apple has an min macOS Version check in the updater/installer). So my Xcode on the high Sierra hackintosh is stuck on an older version, whondering if that means that swift is also stuck on an older version. Gonna take a look today evening.

Thanks for merging the explicit returns into the codebase!

**Comment by gingerr** [comment]
@lwouis Alright I've looked into it.

High Sierra is stuck on Xcode 10.1 which bundles Swift 4.2.1 which probably does not support closures. 

If I would have to I could attempt to upgrade my Hackintosh to Catalina or get with a workaround the latest Xcode running on my system so I get the latest Swift library.

**Comment by lwouis** [comment]
Apple developper ecosystem is one of the worst I've experienced so far. People complain about JavaScript fatigue but this is way worse 🙉

**Pull request merged**
