### PR TITLE
Native support apple silicon

### PR DESCRIPTION
**Pull request by lwouis**
Culmination of https://github.com/lwouis/alt-tab-macos/pull/771 and https://github.com/lwouis/alt-tab-macos/pull/1094. Both authors were credited in the git history accordingly. I even used Github's `Co-authored-by` feature~

### CODE REVIEW

**Comment by mnin** [comment]
@lwouis thanks for your work!

But we got the same issue, something is still wrong in the xcodeproj settings:

```shell
+file /Users/travis/build/[secure]/alt-tab-macos/DerivedData/Build/Products/Debug/AltTab.app/Contents/MacOS/AltTab
3209/Users/travis/build/[secure]/alt-tab-macos/DerivedData/Build/Products/Debug/AltTab.app/Contents/MacOS/AltTab: Mach-O 64-bit executable x86_64
3210
```

So still no arm binary is included, I will have a look later on with my PR and see how I can fix this.

**Comment by lwouis** [comment]
@mnin I think the issue was that the PR builds are DEBUG. I switch PR builds to RELEASE like release builds. On RELEASE, it should build both archs.

**Comment by mnin** [comment]
> @mnin I think the issue was that the PR builds are DEBUG. I switch PR builds to RELEASE like release builds. On RELEASE, it should build both archs.

watching now the second build ;-)

**Comment by mnin** [comment]
@lwouis nice!

```shell
+file /Users/travis/build/[secure]/alt-tab-macos/DerivedData/Build/Products/Release/AltTab.app/Contents/MacOS/AltTab
3113/Users/travis/build/[secure]/alt-tab-macos/DerivedData/Build/Products/Release/AltTab.app/Contents/MacOS/AltTab: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
3114/Users/travis/build/[secure]/alt-tab-macos/DerivedData/Build/Products/Release/AltTab.app/Contents/MacOS/AltTab (for architecture x86_64):	Mach-O 64-bit executable x86_64
3115/Users/travis/build/[secure]/alt-tab-macos/DerivedData/Build/Products/Release/AltTab.app/Contents/MacOS/AltTab (for architecture arm64):	Mach-O 64-bit executable arm64
3116
```

**Comment by lwouis** [comment]
Ok I'll merge on master to release the app then. It's always stressful to release where there is a large change and a CI change, but this seems like a good time to do it to me. Everything has been nicely tested, so hopefully it doesn't break for everyone 🤞

**Comment by gdubicki** [comment]
The download button in https://alt-tab-macos.netlify.app/ still points to old https://github.com/lwouis/alt-tab-macos/releases/download/v6.27.1/AltTab-6.27.1.zip .

**Comment by lwouis** [comment]
@gdubicki thank you very much for pointing it out. I checked the Jenkill/Netlify setup, and it's all correct. I think what happened is that Github was slow to update its internal state after the release was pushed there, and Netlify published the website before that was done, so with the previous version?

I redeployed on Netlify manually, and it's up-to-date now. Thanks again for noticing and telling me!

**Pull request merged**
